"""Pre-designed persona archetypes. The foundation of every simulation.

100 psychographic archetypes organized into 10 categories:
- Core (1-10): The original foundational archetypes
- Decision Makers (11-20): How people make purchase decisions
- Professional Roles (21-30): Job-function-driven behavior
- Emotional Profiles (31-40): Feeling-driven engagement patterns
- Social Dynamics (41-50): How people interact in groups
- Cultural & Identity (51-60): Values and worldview-driven behavior
- Use Case Driven (61-70): Usage-pattern-based archetypes
- Market Psychology (71-80): Economic and buying psychology
- Edge Cases & Wildcards (81-90): Uncommon but real personas
- Platform & Channel (91-100): How people relate to media and platforms
"""

from dataclasses import dataclass


@dataclass
class Archetype:
    id: str
    name: str
    description: str
    engagement_rate: float  # base probability of engaging with content (0-1)
    share_rate: float  # probability of sharing if engaged (0-1)
    objection_tendency: float  # how likely to raise objections (0-1)
    influence_weight: float  # how much their actions affect others (0-1)
    communication_style: str  # how they express themselves


ARCHETYPES: dict[str, Archetype] = {
    # ──────────────────────────────────────────────────────────────────────
    # CORE (1-10) — The original foundational archetypes
    # ──────────────────────────────────────────────────────────────────────
    "skeptic": Archetype(
        id="skeptic",
        name="The Skeptic",
        description="Needs proof, asks hard questions, resistant to hype",
        engagement_rate=0.35,
        share_rate=0.10,
        objection_tendency=0.85,
        influence_weight=0.6,
        communication_style="direct, questioning, demands evidence",
    ),
    "early_adopter": Archetype(
        id="early_adopter",
        name="The Early Adopter",
        description="Excited by novelty, forgives rough edges, shares discoveries",
        engagement_rate=0.70,
        share_rate=0.60,
        objection_tendency=0.15,
        influence_weight=0.7,
        communication_style="enthusiastic, forward-looking, uses superlatives",
    ),
    "pragmatist": Archetype(
        id="pragmatist",
        name="The Pragmatist",
        description="Does it solve my problem? ROI-focused, comparison shopper",
        engagement_rate=0.40,
        share_rate=0.20,
        objection_tendency=0.50,
        influence_weight=0.5,
        communication_style="measured, practical, asks about specifics",
    ),
    "loyalist": Archetype(
        id="loyalist",
        name="The Loyalist",
        description="Brand-attached, defensive of current tools, high switching cost",
        engagement_rate=0.25,
        share_rate=0.15,
        objection_tendency=0.70,
        influence_weight=0.4,
        communication_style="comparative, defensive, mentions incumbent tools",
    ),
    "influencer": Archetype(
        id="influencer",
        name="The Influencer",
        description="Shares opinions publicly, shapes others' views, status-driven",
        engagement_rate=0.80,
        share_rate=0.75,
        objection_tendency=0.25,
        influence_weight=0.9,
        communication_style="opinionated, public-facing, creates threads",
    ),
    "lurker": Archetype(
        id="lurker",
        name="The Lurker",
        description="Reads everything, shares nothing, decides privately",
        engagement_rate=0.10,
        share_rate=0.02,
        objection_tendency=0.05,
        influence_weight=0.1,
        communication_style="silent, occasional like, rarely comments",
    ),
    "budget_conscious": Archetype(
        id="budget_conscious",
        name="The Budget-Conscious",
        description="Price-sensitive, hunts deals, needs justification",
        engagement_rate=0.35,
        share_rate=0.25,
        objection_tendency=0.60,
        influence_weight=0.4,
        communication_style="asks about pricing, compares value, mentions alternatives",
    ),
    "expert": Archetype(
        id="expert",
        name="The Expert",
        description="Deep domain knowledge, detects BS instantly, values precision",
        engagement_rate=0.45,
        share_rate=0.30,
        objection_tendency=0.75,
        influence_weight=0.8,
        communication_style="technical, precise, corrects inaccuracies",
    ),
    "overwhelmed": Archetype(
        id="overwhelmed",
        name="The Overwhelmed",
        description="Too many options, decision fatigue, wants simplicity",
        engagement_rate=0.15,
        share_rate=0.05,
        objection_tendency=0.20,
        influence_weight=0.2,
        communication_style="confused, asks basic questions, wants summaries",
    ),
    "aspirational": Archetype(
        id="aspirational",
        name="The Aspirational",
        description="Wants to level up, motivated by success stories",
        engagement_rate=0.55,
        share_rate=0.45,
        objection_tendency=0.15,
        influence_weight=0.5,
        communication_style="optimistic, references goals, inspired by results",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # DECISION MAKERS (11-20) — How people make purchase decisions
    # ──────────────────────────────────────────────────────────────────────
    "contrarian": Archetype(
        id="contrarian",
        name="The Contrarian",
        description="Disagrees on principle, plays devil's advocate, contrarian for sport",
        engagement_rate=0.55,
        share_rate=0.35,
        objection_tendency=0.90,
        influence_weight=0.6,
        communication_style="argumentative, provocative, challenges every claim",
    ),
    "researcher": Archetype(
        id="researcher",
        name="The Researcher",
        description="Deep-dives before deciding, opens 20 tabs, compares obsessively",
        engagement_rate=0.30,
        share_rate=0.15,
        objection_tendency=0.45,
        influence_weight=0.5,
        communication_style="thorough, asks detailed questions, cites sources",
    ),
    "impulse_buyer": Archetype(
        id="impulse_buyer",
        name="The Impulse Buyer",
        description="Fast decisions, emotional triggers, low deliberation",
        engagement_rate=0.65,
        share_rate=0.40,
        objection_tendency=0.10,
        influence_weight=0.3,
        communication_style="excitable, short attention span, reacts to visuals",
    ),
    "gatekeeper": Archetype(
        id="gatekeeper",
        name="The Gatekeeper",
        description="Buys for teams, needs to justify to stakeholders, risk-averse",
        engagement_rate=0.30,
        share_rate=0.10,
        objection_tendency=0.65,
        influence_weight=0.7,
        communication_style="formal, risk-aware, asks about compliance and security",
    ),
    "burned": Archetype(
        id="burned",
        name="The Burned",
        description="Got wrecked by a similar product, trust near zero, scars from past",
        engagement_rate=0.20,
        share_rate=0.08,
        objection_tendency=0.90,
        influence_weight=0.5,
        communication_style="wary, references past failures, demands guarantees",
    ),
    "champion": Archetype(
        id="champion",
        name="The Champion",
        description="Already loves you, wants to evangelize internally, your biggest fan",
        engagement_rate=0.85,
        share_rate=0.80,
        objection_tendency=0.05,
        influence_weight=0.8,
        communication_style="passionate, defends brand, recruits others",
    ),
    "trendwatcher": Archetype(
        id="trendwatcher",
        name="The Trendwatcher",
        description="Follows what's hot, driven by social proof and FOMO",
        engagement_rate=0.60,
        share_rate=0.55,
        objection_tendency=0.15,
        influence_weight=0.6,
        communication_style="trend-aware, drops buzzwords, references what's popular",
    ),
    "values_driven": Archetype(
        id="values_driven",
        name="The Values-Driven",
        description="Checks your ethics, sustainability, and social impact before features",
        engagement_rate=0.40,
        share_rate=0.35,
        objection_tendency=0.55,
        influence_weight=0.5,
        communication_style="principled, asks about values, flags ethical concerns",
    ),
    "technical_evaluator": Archetype(
        id="technical_evaluator",
        name="The Technical Evaluator",
        description="Needs architecture diagrams, API docs, and integration guides before pricing",
        engagement_rate=0.35,
        share_rate=0.20,
        objection_tendency=0.70,
        influence_weight=0.7,
        communication_style="technical, asks about APIs, wants documentation",
    ),
    "community_seeker": Archetype(
        id="community_seeker",
        name="The Community Seeker",
        description="Wants to belong, motivated by shared identity and user communities",
        engagement_rate=0.50,
        share_rate=0.45,
        objection_tendency=0.15,
        influence_weight=0.4,
        communication_style="social, references community, values belonging",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # PROFESSIONAL ROLES (21-30) — Job-function-driven behavior
    # ──────────────────────────────────────────────────────────────────────
    "cto": Archetype(
        id="cto",
        name="The CTO",
        description="Technical architecture decisions, scalability concerns, build vs buy",
        engagement_rate=0.40,
        share_rate=0.25,
        objection_tendency=0.65,
        influence_weight=0.85,
        communication_style="strategic-technical, asks about scale, architecture, team fit",
    ),
    "cmo": Archetype(
        id="cmo",
        name="The CMO",
        description="Brand positioning, messaging quality, market differentiation focus",
        engagement_rate=0.50,
        share_rate=0.40,
        objection_tendency=0.45,
        influence_weight=0.75,
        communication_style="brand-aware, critiques messaging, thinks in campaigns",
    ),
    "cfo": Archetype(
        id="cfo",
        name="The CFO",
        description="Pure financial metrics, ROI calculations, total cost of ownership",
        engagement_rate=0.25,
        share_rate=0.10,
        objection_tendency=0.75,
        influence_weight=0.80,
        communication_style="numbers-driven, asks about ROI, TCO, payback period",
    ),
    "founder": Archetype(
        id="founder",
        name="The Founder",
        description="Vision-driven, speed-focused, risk-tolerant, wears many hats",
        engagement_rate=0.60,
        share_rate=0.50,
        objection_tendency=0.30,
        influence_weight=0.75,
        communication_style="vision-oriented, time-pressed, wants quick wins",
    ),
    "intern": Archetype(
        id="intern",
        name="The Intern",
        description="Learning the ropes, impressionable, follows seniors, eager to please",
        engagement_rate=0.45,
        share_rate=0.30,
        objection_tendency=0.10,
        influence_weight=0.15,
        communication_style="deferential, asks basic questions, echoes team leads",
    ),
    "consultant": Archetype(
        id="consultant",
        name="The Consultant",
        description="Recommends to clients, needs to look smart, framework-heavy",
        engagement_rate=0.45,
        share_rate=0.35,
        objection_tendency=0.50,
        influence_weight=0.70,
        communication_style="advisory, uses frameworks, positions as expert recommendation",
    ),
    "procurement_officer": Archetype(
        id="procurement_officer",
        name="The Procurement Officer",
        description="Process-driven, compliance-focused, vendor evaluation scorecards",
        engagement_rate=0.20,
        share_rate=0.05,
        objection_tendency=0.70,
        influence_weight=0.65,
        communication_style="formal, process-oriented, asks about certifications",
    ),
    "devops_engineer": Archetype(
        id="devops_engineer",
        name="The DevOps Engineer",
        description="Reliability, uptime, monitoring, incident response, infrastructure",
        engagement_rate=0.35,
        share_rate=0.20,
        objection_tendency=0.60,
        influence_weight=0.55,
        communication_style="operational, asks about SLAs, uptime, deployment",
    ),
    "designer": Archetype(
        id="designer",
        name="The Designer",
        description="UX/UI quality, aesthetics, user experience, design system fit",
        engagement_rate=0.50,
        share_rate=0.40,
        objection_tendency=0.40,
        influence_weight=0.50,
        communication_style="visual-first, critiques UX, references design patterns",
    ),
    "sales_rep": Archetype(
        id="sales_rep",
        name="The Sales Rep",
        description="Needs tools that help close deals, quota-driven, client-facing",
        engagement_rate=0.55,
        share_rate=0.35,
        objection_tendency=0.35,
        influence_weight=0.45,
        communication_style="results-focused, asks about client impact, competitive edge",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # EMOTIONAL PROFILES (31-40) — Feeling-driven engagement patterns
    # ──────────────────────────────────────────────────────────────────────
    "anxious": Archetype(
        id="anxious",
        name="The Anxious",
        description="Worst-case thinker, needs reassurance, fears making wrong choice",
        engagement_rate=0.25,
        share_rate=0.08,
        objection_tendency=0.60,
        influence_weight=0.25,
        communication_style="worried, asks about risks, needs safety nets",
    ),
    "enthusiast": Archetype(
        id="enthusiast",
        name="The Enthusiast",
        description="Gets excited about everything, short attention span, high initial energy",
        engagement_rate=0.75,
        share_rate=0.60,
        objection_tendency=0.10,
        influence_weight=0.45,
        communication_style="excited, uses exclamation marks, jumps between features",
    ),
    "cynic": Archetype(
        id="cynic",
        name="The Cynic",
        description="Assumes worst motives, 'they're just after your money', trust-resistant",
        engagement_rate=0.30,
        share_rate=0.15,
        objection_tendency=0.85,
        influence_weight=0.50,
        communication_style="dismissive, questions motives, sarcastic",
    ),
    "optimist": Archetype(
        id="optimist",
        name="The Optimist",
        description="Sees potential everywhere, gives benefit of the doubt, maybe too trusting",
        engagement_rate=0.60,
        share_rate=0.45,
        objection_tendency=0.10,
        influence_weight=0.40,
        communication_style="positive, supportive, focuses on upside",
    ),
    "perfectionist": Archetype(
        id="perfectionist",
        name="The Perfectionist",
        description="Nothing is ever good enough, finds flaws in everything, high standards",
        engagement_rate=0.35,
        share_rate=0.10,
        objection_tendency=0.80,
        influence_weight=0.55,
        communication_style="critical, detailed, points out every imperfection",
    ),
    "nostalgic": Archetype(
        id="nostalgic",
        name="The Nostalgic",
        description="'Things were better before,' prefers legacy, resistant to change",
        engagement_rate=0.20,
        share_rate=0.10,
        objection_tendency=0.65,
        influence_weight=0.35,
        communication_style="comparative to past, references 'the old way', resistant",
    ),
    "competitive": Archetype(
        id="competitive",
        name="The Competitive",
        description="Wants what gives them an edge, status-conscious, winning matters",
        engagement_rate=0.50,
        share_rate=0.30,
        objection_tendency=0.35,
        influence_weight=0.55,
        communication_style="comparative, asks 'what edge does this give me?', ambitious",
    ),
    "empathetic": Archetype(
        id="empathetic",
        name="The Empathetic",
        description="Cares about team impact, user experience, how change affects people",
        engagement_rate=0.45,
        share_rate=0.35,
        objection_tendency=0.30,
        influence_weight=0.45,
        communication_style="people-focused, asks about user impact, considerate",
    ),
    "frustrated": Archetype(
        id="frustrated",
        name="The Frustrated",
        description="Current solution is painful, actively looking for relief, high urgency",
        engagement_rate=0.65,
        share_rate=0.30,
        objection_tendency=0.40,
        influence_weight=0.45,
        communication_style="urgent, vents about current pain, wants solutions now",
    ),
    "curious": Archetype(
        id="curious",
        name="The Curious",
        description="Explores for fun, not necessarily to buy, intellectually driven",
        engagement_rate=0.55,
        share_rate=0.25,
        objection_tendency=0.20,
        influence_weight=0.35,
        communication_style="inquisitive, asks 'how does it work?', exploratory",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # SOCIAL DYNAMICS (41-50) — How people interact in groups
    # ──────────────────────────────────────────────────────────────────────
    "hype_man": Archetype(
        id="hype_man",
        name="The Hype Man",
        description="Amplifies everything positively, adds energy, creates buzz",
        engagement_rate=0.80,
        share_rate=0.70,
        objection_tendency=0.05,
        influence_weight=0.65,
        communication_style="high-energy, uses caps, creates excitement",
    ),
    "troll": Archetype(
        id="troll",
        name="The Troll",
        description="Provocative, derails conversations, tests patience, chaos agent",
        engagement_rate=0.70,
        share_rate=0.40,
        objection_tendency=0.80,
        influence_weight=0.50,
        communication_style="provocative, off-topic, inflammatory, sarcastic",
    ),
    "mediator": Archetype(
        id="mediator",
        name="The Mediator",
        description="De-escalates, finds middle ground, bridges opposing views",
        engagement_rate=0.45,
        share_rate=0.20,
        objection_tendency=0.15,
        influence_weight=0.55,
        communication_style="diplomatic, acknowledges both sides, seeks consensus",
    ),
    "broadcaster": Archetype(
        id="broadcaster",
        name="The Broadcaster",
        description="One-way communication, posts but doesn't engage with replies",
        engagement_rate=0.40,
        share_rate=0.55,
        objection_tendency=0.20,
        influence_weight=0.45,
        communication_style="declarative, makes announcements, doesn't discuss",
    ),
    "networker": Archetype(
        id="networker",
        name="The Networker",
        description="Connects people, 'you should talk to...', relationship-driven",
        engagement_rate=0.60,
        share_rate=0.65,
        objection_tendency=0.15,
        influence_weight=0.70,
        communication_style="connective, tags people, makes introductions",
    ),
    "silent_majority": Archetype(
        id="silent_majority",
        name="The Silent Majority",
        description="Average user, neither loud nor quiet, represents the mainstream",
        engagement_rate=0.25,
        share_rate=0.10,
        objection_tendency=0.30,
        influence_weight=0.20,
        communication_style="unremarkable, occasional comments, goes with the flow",
    ),
    "follower": Archetype(
        id="follower",
        name="The Follower",
        description="Adopts what the group adopts, social proof dependent, consensus-driven",
        engagement_rate=0.30,
        share_rate=0.20,
        objection_tendency=0.10,
        influence_weight=0.15,
        communication_style="agreeable, echoes popular opinions, 'me too'",
    ),
    "rebel": Archetype(
        id="rebel",
        name="The Rebel",
        description="Rejects mainstream, alternative identity, anti-establishment",
        engagement_rate=0.45,
        share_rate=0.30,
        objection_tendency=0.70,
        influence_weight=0.50,
        communication_style="counter-culture, dismisses popular things, indie preference",
    ),
    "mentor": Archetype(
        id="mentor",
        name="The Mentor",
        description="Helps others decide, shares experience, senior perspective",
        engagement_rate=0.50,
        share_rate=0.35,
        objection_tendency=0.40,
        influence_weight=0.75,
        communication_style="advisory, shares anecdotes, 'in my experience...'",
    ),
    "newbie": Archetype(
        id="newbie",
        name="The Newbie",
        description="Brand new to the category, needs education, no preconceptions",
        engagement_rate=0.40,
        share_rate=0.15,
        objection_tendency=0.10,
        influence_weight=0.10,
        communication_style="questioning, needs basics explained, easily impressed or confused",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # CULTURAL & IDENTITY (51-60) — Values and worldview-driven behavior
    # ──────────────────────────────────────────────────────────────────────
    "digital_native": Archetype(
        id="digital_native",
        name="The Digital Native",
        description="Born online, expects instant everything, mobile-first, app-native",
        engagement_rate=0.65,
        share_rate=0.50,
        objection_tendency=0.20,
        influence_weight=0.40,
        communication_style="casual, emoji-comfortable, expects modern UX",
    ),
    "late_adopter": Archetype(
        id="late_adopter",
        name="The Late Adopter",
        description="Waits until something is mainstream and proven, no bleeding edge",
        engagement_rate=0.15,
        share_rate=0.05,
        objection_tendency=0.55,
        influence_weight=0.25,
        communication_style="cautious, asks 'who else uses this?', wants maturity",
    ),
    "global_citizen": Archetype(
        id="global_citizen",
        name="The Global Citizen",
        description="International perspective, localization matters, culturally aware",
        engagement_rate=0.40,
        share_rate=0.30,
        objection_tendency=0.35,
        influence_weight=0.45,
        communication_style="internationally minded, asks about localization, multi-lingual",
    ),
    "local_first": Archetype(
        id="local_first",
        name="The Local-First",
        description="Prefers local/regional solutions, supports home-grown, community-oriented",
        engagement_rate=0.35,
        share_rate=0.25,
        objection_tendency=0.40,
        influence_weight=0.35,
        communication_style="community-focused, asks about local presence, regional pride",
    ),
    "privacy_advocate": Archetype(
        id="privacy_advocate",
        name="The Privacy Advocate",
        description="Data privacy paramount, suspicious of tracking, reads ToS",
        engagement_rate=0.30,
        share_rate=0.15,
        objection_tendency=0.75,
        influence_weight=0.55,
        communication_style="privacy-focused, asks about data handling, GDPR-aware",
    ),
    "open_source_purist": Archetype(
        id="open_source_purist",
        name="The Open Source Purist",
        description="Prefers open solutions, suspicious of proprietary lock-in, community-built",
        engagement_rate=0.40,
        share_rate=0.30,
        objection_tendency=0.65,
        influence_weight=0.55,
        communication_style="asks about source code, licensing, vendor lock-in",
    ),
    "enterprise_veteran": Archetype(
        id="enterprise_veteran",
        name="The Enterprise Veteran",
        description="Used to big vendor relationships, expects hand-holding, wants support SLAs",
        engagement_rate=0.25,
        share_rate=0.10,
        objection_tendency=0.55,
        influence_weight=0.50,
        communication_style="formal, asks about support tiers, expects account managers",
    ),
    "startup_culture": Archetype(
        id="startup_culture",
        name="The Startup Culture",
        description="Fast, scrappy, move fast and break things, values velocity over polish",
        engagement_rate=0.65,
        share_rate=0.50,
        objection_tendency=0.20,
        influence_weight=0.45,
        communication_style="informal, speed-focused, tolerates rough edges",
    ),
    "academic": Archetype(
        id="academic",
        name="The Academic",
        description="Theoretical, research-oriented, wants papers and evidence, peer-reviewed",
        engagement_rate=0.30,
        share_rate=0.20,
        objection_tendency=0.60,
        influence_weight=0.50,
        communication_style="scholarly, asks for research backing, methodological",
    ),
    "regulator": Archetype(
        id="regulator",
        name="The Regulator",
        description="Compliance, regulations, governance-focused, risk mitigation",
        engagement_rate=0.20,
        share_rate=0.05,
        objection_tendency=0.80,
        influence_weight=0.70,
        communication_style="compliance-focused, asks about regulations, audit-ready",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # USE CASE DRIVEN (61-70) — Usage-pattern-based archetypes
    # ──────────────────────────────────────────────────────────────────────
    "power_user": Archetype(
        id="power_user",
        name="The Power User",
        description="Pushes limits, wants advanced features, keyboard shortcuts, hidden settings",
        engagement_rate=0.55,
        share_rate=0.35,
        objection_tendency=0.50,
        influence_weight=0.65,
        communication_style="advanced, asks about edge cases, wants depth",
    ),
    "casual_user": Archetype(
        id="casual_user",
        name="The Casual User",
        description="Light usage, basic needs, doesn't care about depth or power features",
        engagement_rate=0.20,
        share_rate=0.10,
        objection_tendency=0.15,
        influence_weight=0.15,
        communication_style="simple, uses basics, doesn't read docs",
    ),
    "migrator": Archetype(
        id="migrator",
        name="The Migrator",
        description="Currently switching from another tool, needs migration path, comparison-heavy",
        engagement_rate=0.50,
        share_rate=0.20,
        objection_tendency=0.55,
        influence_weight=0.40,
        communication_style="comparative, asks about migration, references old tool",
    ),
    "multi_tool_user": Archetype(
        id="multi_tool_user",
        name="The Multi-Tool User",
        description="Uses many tools, wants integrations, API-first, workflow-oriented",
        engagement_rate=0.45,
        share_rate=0.25,
        objection_tendency=0.45,
        influence_weight=0.50,
        communication_style="integration-focused, asks about APIs, mentions other tools",
    ),
    "solo_operator": Archetype(
        id="solo_operator",
        name="The Solo Operator",
        description="One-person show, needs all-in-one, can't afford specialization",
        engagement_rate=0.45,
        share_rate=0.30,
        objection_tendency=0.35,
        influence_weight=0.30,
        communication_style="practical, asks about all-in-one, time-constrained",
    ),
    "team_lead": Archetype(
        id="team_lead",
        name="The Team Lead",
        description="Evaluating for a team, coordination needs, onboarding concerns",
        engagement_rate=0.40,
        share_rate=0.20,
        objection_tendency=0.50,
        influence_weight=0.65,
        communication_style="team-focused, asks about collaboration, onboarding",
    ),
    "agency_client": Archetype(
        id="agency_client",
        name="The Agency Client",
        description="Evaluating for client work, multi-tenant, scale and white-label matter",
        engagement_rate=0.35,
        share_rate=0.20,
        objection_tendency=0.50,
        influence_weight=0.55,
        communication_style="client-oriented, asks about white-labeling, multi-account",
    ),
    "formal_evaluator": Archetype(
        id="formal_evaluator",
        name="The Formal Evaluator",
        description="In a formal evaluation process, has a scorecard, structured comparison",
        engagement_rate=0.30,
        share_rate=0.10,
        objection_tendency=0.60,
        influence_weight=0.60,
        communication_style="structured, systematic, asks checklist questions",
    ),
    "renewal_risk": Archetype(
        id="renewal_risk",
        name="The Renewal Risk",
        description="Current customer considering leaving, dissatisfied, comparing alternatives",
        engagement_rate=0.50,
        share_rate=0.15,
        objection_tendency=0.75,
        influence_weight=0.45,
        communication_style="disappointed, references unmet promises, comparing options",
    ),
    "comeback": Archetype(
        id="comeback",
        name="The Comeback",
        description="Left before, considering returning, needs proof things changed",
        engagement_rate=0.35,
        share_rate=0.15,
        objection_tendency=0.65,
        influence_weight=0.40,
        communication_style="cautious optimism, references past issues, wants changelogs",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # MARKET PSYCHOLOGY (71-80) — Economic and buying psychology
    # ──────────────────────────────────────────────────────────────────────
    "fomo_victim": Archetype(
        id="fomo_victim",
        name="The FOMO Victim",
        description="Fear of missing out drives decisions, urgency-responsive, herd mentality",
        engagement_rate=0.60,
        share_rate=0.45,
        objection_tendency=0.10,
        influence_weight=0.30,
        communication_style="urgent, asks 'am I too late?', references others adopting",
    ),
    "status_seeker": Archetype(
        id="status_seeker",
        name="The Status Seeker",
        description="Brand as signal, premium positioning matters, wants exclusivity",
        engagement_rate=0.55,
        share_rate=0.50,
        objection_tendency=0.25,
        influence_weight=0.55,
        communication_style="status-conscious, asks about premium tiers, brand-aware",
    ),
    "practical_parent": Archetype(
        id="practical_parent",
        name="The Practical Parent",
        description="Time-poor, needs things that just work, zero patience for complexity",
        engagement_rate=0.25,
        share_rate=0.15,
        objection_tendency=0.45,
        influence_weight=0.30,
        communication_style="time-pressed, asks about ease of use, needs simplicity",
    ),
    "student_budget": Archetype(
        id="student_budget",
        name="The Student Budget",
        description="Young, broke, wants free tier or edu discount, scrappy resourceful",
        engagement_rate=0.50,
        share_rate=0.35,
        objection_tendency=0.35,
        influence_weight=0.20,
        communication_style="price-focused, asks about free plans, student discounts",
    ),
    "corporate_card": Archetype(
        id="corporate_card",
        name="The Corporate Card",
        description="Spending someone else's money, less price-sensitive, expense-account buyer",
        engagement_rate=0.45,
        share_rate=0.20,
        objection_tendency=0.25,
        influence_weight=0.40,
        communication_style="casual about price, focused on features, needs invoice",
    ),
    "comparison_shopper": Archetype(
        id="comparison_shopper",
        name="The Comparison Shopper",
        description="Has a spreadsheet, feature-by-feature comparison, methodical evaluation",
        engagement_rate=0.35,
        share_rate=0.15,
        objection_tendency=0.55,
        influence_weight=0.45,
        communication_style="systematic, asks about specific features, creates matrices",
    ),
    "referral": Archetype(
        id="referral",
        name="The Referral",
        description="Came via word of mouth, already somewhat trusting, warm lead",
        engagement_rate=0.55,
        share_rate=0.30,
        objection_tendency=0.20,
        influence_weight=0.35,
        communication_style="mentions who referred them, already partially sold",
    ),
    "ad_skeptic": Archetype(
        id="ad_skeptic",
        name="The Ad-Skeptic",
        description="Distrusts all advertising, blocks ads, hates being pitched to",
        engagement_rate=0.15,
        share_rate=0.05,
        objection_tendency=0.80,
        influence_weight=0.40,
        communication_style="dismissive of marketing, wants raw truth, hates spin",
    ),
    "content_creator": Archetype(
        id="content_creator",
        name="The Content Creator",
        description="Evaluates based on content creation potential, audience-aware, platform-savvy",
        engagement_rate=0.65,
        share_rate=0.60,
        objection_tendency=0.25,
        influence_weight=0.65,
        communication_style="audience-focused, thinks in content, asks about creator tools",
    ),
    "analyst": Archetype(
        id="analyst",
        name="The Analyst",
        description="Data-obsessed, wants dashboards and metrics before committing",
        engagement_rate=0.35,
        share_rate=0.15,
        objection_tendency=0.55,
        influence_weight=0.55,
        communication_style="data-driven, asks for metrics, wants benchmarks",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # EDGE CASES & WILDCARDS (81-90) — Uncommon but real personas
    # ──────────────────────────────────────────────────────────────────────
    "accessibility_advocate": Archetype(
        id="accessibility_advocate",
        name="The Accessibility Advocate",
        description="Evaluates for disability support, a11y compliance, inclusive design",
        engagement_rate=0.40,
        share_rate=0.30,
        objection_tendency=0.60,
        influence_weight=0.50,
        communication_style="inclusion-focused, asks about a11y, tests with screen readers",
    ),
    "sustainability_hawk": Archetype(
        id="sustainability_hawk",
        name="The Sustainability Hawk",
        description="Carbon footprint, green credentials, environmental responsibility matters",
        engagement_rate=0.35,
        share_rate=0.30,
        objection_tendency=0.55,
        influence_weight=0.45,
        communication_style="environment-conscious, asks about sustainability, green signals",
    ),
    "speed_demon": Archetype(
        id="speed_demon",
        name="The Speed Demon",
        description="Performance is everything, milliseconds matter, hates loading spinners",
        engagement_rate=0.45,
        share_rate=0.25,
        objection_tendency=0.60,
        influence_weight=0.45,
        communication_style="performance-focused, benchmarks everything, hates bloat",
    ),
    "security_paranoid": Archetype(
        id="security_paranoid",
        name="The Security Paranoid",
        description="Security posture is #1, wants pen test results, SOC 2, zero trust",
        engagement_rate=0.25,
        share_rate=0.10,
        objection_tendency=0.85,
        influence_weight=0.60,
        communication_style="security-first, asks about encryption, audit logs, compliance",
    ),
    "data_hoarder": Archetype(
        id="data_hoarder",
        name="The Data Hoarder",
        description="Wants to keep and export everything, no lock-in, data portability",
        engagement_rate=0.35,
        share_rate=0.15,
        objection_tendency=0.55,
        influence_weight=0.40,
        communication_style="asks about data export, portability, backup options",
    ),
    "automation_junkie": Archetype(
        id="automation_junkie",
        name="The Automation Junkie",
        description="Wants APIs, webhooks, Zapier, no manual work, automate everything",
        engagement_rate=0.50,
        share_rate=0.30,
        objection_tendency=0.40,
        influence_weight=0.50,
        communication_style="automation-focused, asks about APIs, webhooks, integrations",
    ),
    "visual_thinker": Archetype(
        id="visual_thinker",
        name="The Visual Thinker",
        description="Needs demos, screenshots, videos, not text walls, show don't tell",
        engagement_rate=0.50,
        share_rate=0.35,
        objection_tendency=0.20,
        influence_weight=0.35,
        communication_style="asks for demos, screenshots, videos, skips text",
    ),
    "risk_manager": Archetype(
        id="risk_manager",
        name="The Risk Manager",
        description="Identifies risks, wants contingency plans, what-if scenarios",
        engagement_rate=0.30,
        share_rate=0.10,
        objection_tendency=0.70,
        influence_weight=0.60,
        communication_style="risk-focused, asks about failure modes, disaster recovery",
    ),
    "early_churner": Archetype(
        id="early_churner",
        name="The Early Churner",
        description="Signs up fast, cancels faster, low commitment, serial trial user",
        engagement_rate=0.60,
        share_rate=0.20,
        objection_tendency=0.15,
        influence_weight=0.20,
        communication_style="noncommittal, asks about cancellation, trial-focused",
    ),
    "sleeper": Archetype(
        id="sleeper",
        name="The Sleeper",
        description="Registers, goes dormant, might activate later, lurks then surprises",
        engagement_rate=0.05,
        share_rate=0.02,
        objection_tendency=0.10,
        influence_weight=0.10,
        communication_style="rare engagement, long gaps, re-emerges unexpectedly",
    ),

    # ──────────────────────────────────────────────────────────────────────
    # PLATFORM & CHANNEL (91-100) — How people relate to media and platforms
    # ──────────────────────────────────────────────────────────────────────
    "twitter_native": Archetype(
        id="twitter_native",
        name="The Twitter/X Native",
        description="Thinks in threads, hot takes, ratio culture, real-time discourse",
        engagement_rate=0.70,
        share_rate=0.65,
        objection_tendency=0.45,
        influence_weight=0.60,
        communication_style="punchy, thread-style, hot takes, quote-tweets",
    ),
    "linkedin_professional": Archetype(
        id="linkedin_professional",
        name="The LinkedIn Professional",
        description="Corporate-polished, humble-brag, thought leadership, professional network",
        engagement_rate=0.45,
        share_rate=0.40,
        objection_tendency=0.20,
        influence_weight=0.50,
        communication_style="professional, adds 'thoughts?', humble-brags, tags companies",
    ),
    "reddit_diver": Archetype(
        id="reddit_diver",
        name="The Reddit Diver",
        description="Pseudonymous, detail-oriented, sniffs out astroturfing, community-loyal",
        engagement_rate=0.50,
        share_rate=0.25,
        objection_tendency=0.70,
        influence_weight=0.55,
        communication_style="detailed, suspicious of marketing, values authenticity",
    ),
    "youtube_learner": Archetype(
        id="youtube_learner",
        name="The YouTube Learner",
        description="Needs video walkthroughs, tutorial-oriented, learns by watching",
        engagement_rate=0.40,
        share_rate=0.20,
        objection_tendency=0.15,
        influence_weight=0.30,
        communication_style="asks for video content, tutorial-oriented, visual learner",
    ),
    "podcast_listener": Archetype(
        id="podcast_listener",
        name="The Podcast Listener",
        description="Influenced by thought leaders, long-form content consumer, narrative-driven",
        engagement_rate=0.35,
        share_rate=0.25,
        objection_tendency=0.25,
        influence_weight=0.40,
        communication_style="references podcasts and thought leaders, narrative-oriented",
    ),
    "newsletter_subscriber": Archetype(
        id="newsletter_subscriber",
        name="The Newsletter Subscriber",
        description="Email-native, curated content consumer, trusts selected voices",
        engagement_rate=0.30,
        share_rate=0.20,
        objection_tendency=0.30,
        influence_weight=0.35,
        communication_style="references newsletters, curated taste, selective attention",
    ),
    "tiktok_native": Archetype(
        id="tiktok_native",
        name="The TikTok Native",
        description="Short-form video consumer, trend-driven, authenticity over polish",
        engagement_rate=0.65,
        share_rate=0.55,
        objection_tendency=0.15,
        influence_weight=0.45,
        communication_style="trend-aware, authenticity-focused, short attention span",
    ),
    "discord_denizen": Archetype(
        id="discord_denizen",
        name="The Discord Denizen",
        description="Community-first, real-time chat culture, wants direct dev access",
        engagement_rate=0.60,
        share_rate=0.40,
        objection_tendency=0.30,
        influence_weight=0.50,
        communication_style="casual, meme-aware, expects dev presence, community-driven",
    ),
    "email_only": Archetype(
        id="email_only",
        name="The Email-Only",
        description="Refuses social media, communicates via email, old-school professional",
        engagement_rate=0.15,
        share_rate=0.05,
        objection_tendency=0.50,
        influence_weight=0.30,
        communication_style="formal, email-style, prefers 1:1 communication",
    ),
    "dark_social": Archetype(
        id="dark_social",
        name="The Dark Social",
        description="Shares via DMs, group chats, private channels — invisible but influential",
        engagement_rate=0.20,
        share_rate=0.60,
        objection_tendency=0.25,
        influence_weight=0.55,
        communication_style="private sharing, DMs links, invisible public footprint",
    ),
}

# Pre-configured industry crowd compositions
INDUSTRY_PACKS: dict[str, dict[str, float]] = {
    "saas_b2b": {
        # Core
        "pragmatist": 0.08,
        "expert": 0.06,
        "budget_conscious": 0.04,
        "skeptic": 0.05,
        "loyalist": 0.03,
        "lurker": 0.04,
        "early_adopter": 0.02,
        # Decision makers
        "gatekeeper": 0.05,
        "technical_evaluator": 0.05,
        "researcher": 0.03,
        "burned": 0.02,
        # Professional roles
        "cto": 0.04,
        "cfo": 0.03,
        "devops_engineer": 0.03,
        "procurement_officer": 0.03,
        "consultant": 0.02,
        "team_lead": 0.03,
        # Emotional
        "frustrated": 0.02,
        "perfectionist": 0.02,
        # Social
        "silent_majority": 0.04,
        "mentor": 0.02,
        # Cultural
        "enterprise_veteran": 0.03,
        "privacy_advocate": 0.02,
        "regulator": 0.02,
        # Use case
        "power_user": 0.02,
        "migrator": 0.02,
        "formal_evaluator": 0.02,
        "renewal_risk": 0.01,
        # Market psychology
        "comparison_shopper": 0.02,
        "analyst": 0.02,
        "corporate_card": 0.02,
        # Edge cases
        "security_paranoid": 0.02,
        "risk_manager": 0.02,
        # Platform
        "linkedin_professional": 0.02,
    },
    "ecommerce_dtc": {
        # Core
        "early_adopter": 0.06,
        "aspirational": 0.06,
        "budget_conscious": 0.06,
        "influencer": 0.05,
        "lurker": 0.04,
        "overwhelmed": 0.04,
        "pragmatist": 0.02,
        # Decision makers
        "impulse_buyer": 0.06,
        "trendwatcher": 0.04,
        "champion": 0.03,
        "values_driven": 0.03,
        "community_seeker": 0.03,
        # Professional roles
        "designer": 0.02,
        "sales_rep": 0.02,
        # Emotional
        "enthusiast": 0.04,
        "optimist": 0.02,
        "curious": 0.02,
        "competitive": 0.02,
        # Social
        "hype_man": 0.03,
        "follower": 0.03,
        "silent_majority": 0.03,
        "networker": 0.02,
        # Cultural
        "digital_native": 0.03,
        "startup_culture": 0.02,
        # Use case
        "casual_user": 0.02,
        "solo_operator": 0.02,
        # Market psychology
        "fomo_victim": 0.03,
        "status_seeker": 0.02,
        "referral": 0.02,
        "content_creator": 0.02,
        "student_budget": 0.02,
        # Edge cases
        "visual_thinker": 0.02,
        "early_churner": 0.02,
        # Platform
        "tiktok_native": 0.02,
        "twitter_native": 0.02,
    },
    "consumer_app": {
        # Core
        "early_adopter": 0.06,
        "lurker": 0.05,
        "influencer": 0.05,
        "aspirational": 0.04,
        "overwhelmed": 0.03,
        "skeptic": 0.02,
        "pragmatist": 0.02,
        # Decision makers
        "impulse_buyer": 0.04,
        "trendwatcher": 0.04,
        "champion": 0.03,
        "community_seeker": 0.03,
        "contrarian": 0.02,
        # Professional roles
        "founder": 0.02,
        "designer": 0.02,
        # Emotional
        "enthusiast": 0.04,
        "curious": 0.03,
        "frustrated": 0.02,
        "optimist": 0.02,
        # Social
        "hype_man": 0.03,
        "follower": 0.03,
        "silent_majority": 0.04,
        "newbie": 0.03,
        "troll": 0.01,
        # Cultural
        "digital_native": 0.04,
        "late_adopter": 0.02,
        "startup_culture": 0.02,
        # Use case
        "power_user": 0.02,
        "casual_user": 0.03,
        "early_churner": 0.02,
        "sleeper": 0.02,
        # Market psychology
        "fomo_victim": 0.02,
        "referral": 0.02,
        "content_creator": 0.02,
        "student_budget": 0.02,
        # Edge cases
        "visual_thinker": 0.02,
        # Platform
        "tiktok_native": 0.02,
        "discord_denizen": 0.02,
        "dark_social": 0.02,
    },
    "developer_tools": {
        # Core
        "expert": 0.08,
        "skeptic": 0.05,
        "early_adopter": 0.05,
        "pragmatist": 0.04,
        "lurker": 0.04,
        # Decision makers
        "technical_evaluator": 0.06,
        "researcher": 0.04,
        "contrarian": 0.02,
        "burned": 0.02,
        # Professional roles
        "cto": 0.04,
        "devops_engineer": 0.04,
        "founder": 0.03,
        "consultant": 0.02,
        # Emotional
        "perfectionist": 0.03,
        "frustrated": 0.03,
        "curious": 0.03,
        # Social
        "mentor": 0.03,
        "rebel": 0.02,
        "silent_majority": 0.03,
        "troll": 0.01,
        # Cultural
        "open_source_purist": 0.05,
        "privacy_advocate": 0.03,
        "startup_culture": 0.02,
        # Use case
        "power_user": 0.04,
        "multi_tool_user": 0.03,
        "automation_junkie": 0.03,
        "migrator": 0.02,
        # Market psychology
        "ad_skeptic": 0.02,
        "comparison_shopper": 0.02,
        # Edge cases
        "speed_demon": 0.03,
        "data_hoarder": 0.02,
        # Platform
        "reddit_diver": 0.03,
        "twitter_native": 0.02,
        "discord_denizen": 0.03,
        "dark_social": 0.02,
    },
    "fintech": {
        # Core
        "skeptic": 0.06,
        "expert": 0.05,
        "pragmatist": 0.05,
        "budget_conscious": 0.04,
        "loyalist": 0.03,
        "lurker": 0.03,
        # Decision makers
        "gatekeeper": 0.04,
        "researcher": 0.04,
        "burned": 0.03,
        "technical_evaluator": 0.03,
        # Professional roles
        "cfo": 0.04,
        "procurement_officer": 0.03,
        "regulator": 0.04,
        "consultant": 0.02,
        # Emotional
        "anxious": 0.03,
        "perfectionist": 0.02,
        "cynic": 0.02,
        # Social
        "silent_majority": 0.04,
        "mediator": 0.02,
        "mentor": 0.02,
        # Cultural
        "privacy_advocate": 0.04,
        "enterprise_veteran": 0.03,
        # Use case
        "formal_evaluator": 0.03,
        "renewal_risk": 0.02,
        "multi_tool_user": 0.02,
        # Market psychology
        "analyst": 0.04,
        "comparison_shopper": 0.03,
        "corporate_card": 0.02,
        "risk_manager": 0.03,
        # Edge cases
        "security_paranoid": 0.04,
        "data_hoarder": 0.02,
        # Platform
        "linkedin_professional": 0.02,
        "newsletter_subscriber": 0.02,
    },
    "health_wellness": {
        # Core
        "aspirational": 0.06,
        "skeptic": 0.04,
        "overwhelmed": 0.04,
        "early_adopter": 0.03,
        "budget_conscious": 0.03,
        "influencer": 0.03,
        # Decision makers
        "values_driven": 0.05,
        "researcher": 0.04,
        "community_seeker": 0.04,
        "champion": 0.03,
        # Professional roles
        "academic": 0.03,
        # Emotional
        "anxious": 0.04,
        "empathetic": 0.04,
        "optimist": 0.03,
        "frustrated": 0.03,
        "curious": 0.02,
        # Social
        "follower": 0.03,
        "networker": 0.02,
        "mentor": 0.02,
        "silent_majority": 0.03,
        # Cultural
        "local_first": 0.02,
        "sustainability_hawk": 0.03,
        "privacy_advocate": 0.02,
        # Use case
        "casual_user": 0.03,
        "solo_operator": 0.02,
        # Market psychology
        "practical_parent": 0.04,
        "referral": 0.03,
        "fomo_victim": 0.02,
        "content_creator": 0.02,
        # Edge cases
        "accessibility_advocate": 0.03,
        "visual_thinker": 0.02,
        "early_churner": 0.02,
        # Platform
        "tiktok_native": 0.02,
        "youtube_learner": 0.03,
        "podcast_listener": 0.02,
    },
    "education": {
        # Core
        "aspirational": 0.05,
        "overwhelmed": 0.04,
        "pragmatist": 0.04,
        "lurker": 0.04,
        "early_adopter": 0.03,
        "budget_conscious": 0.04,
        # Decision makers
        "researcher": 0.04,
        "gatekeeper": 0.03,
        "values_driven": 0.03,
        "community_seeker": 0.03,
        # Professional roles
        "academic": 0.05,
        "intern": 0.03,
        "team_lead": 0.02,
        # Emotional
        "curious": 0.04,
        "empathetic": 0.03,
        "anxious": 0.02,
        "enthusiast": 0.02,
        # Social
        "mentor": 0.04,
        "newbie": 0.04,
        "follower": 0.03,
        "silent_majority": 0.03,
        # Cultural
        "global_citizen": 0.03,
        "accessibility_advocate": 0.03,
        "privacy_advocate": 0.02,
        # Use case
        "casual_user": 0.03,
        "solo_operator": 0.02,
        # Market psychology
        "student_budget": 0.05,
        "practical_parent": 0.03,
        "referral": 0.02,
        # Edge cases
        "visual_thinker": 0.03,
        # Platform
        "youtube_learner": 0.04,
        "discord_denizen": 0.02,
        "tiktok_native": 0.02,
    },
}
